spring:
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/muscle
    username: muscleMan
    password: 175863
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 242213484131-ld9ggephsgb78b0mhq7f3ciar5rmqrf1.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile
